
import { MODE, TOUCH, AVATAR } from '../lib/modes.js';
import { slotRanks, rd, hash01 } from '../lib/sampling.js';
import { textBlock, TEXT_SHARE } from './code-kit.js';
import { portraitSky, PORTRAIT_SPLIT } from './code.js';

/* ==========================================================================
   THE AVATAR: the portrait as a constellation (hero, dach)

   Where the CV carries a photo, the hero draws it in points instead, in the
   medallion's place (cv-universe.js fits the camera to the medallion, see
   lib/modes.js AVATAR). Everything is read from the photo and its depth map,
   as two maps (tone and depth) the source HTML carries in #cv-avatar-data
   (generated by scripts/avatar-data.mjs): inside the document, so the encrypted build ships
   them with the photo they come from, never as a public file in webgl/.
   Nothing is hand-placed but the glasses, which are wire too thin for any map
   at this size. Without the maps (Node, or a page that lacks them) the block
   bakes hidden, and cv-universe.js does not stage the portrait.

   - The photo, point for point. An R2 walk over the photo, each candidate
     kept by a coin weighted by the tone (dense where it is lit, never empty
     where it is dark), and every point's light (its size) follows the tone
     too, so light per area tracks the photo at about display gamma and the
     face reads as the photo rather than as a stylised stipple. Shade cools a
     little toward the accent; nothing else is tinted.
   - The glasses. Two rims, the bridge and the end pieces as fine continuous
     lines on the golden-ratio order (every prefix evenly spaced), lit toward
     the upper right where the photo's rims catch the light, set a little in
     front of the face. Five small stars: both catchlights, both rims' glints
     and the left hinge.
   - Depth, kept low. Every point sits on the depth map's surface, `relief`
     units deep: enough for the face to turn as a surface under the rock and
     the pointer's parallax, not enough to stop reading as the photo. The
     surface is the depth map grown past the silhouette and smoothed (a
     snapped surface moved the map's 128 px cells as blocks and left square
     gaps round the fingers), and the tone at the silhouette is the person's
     own, not the lighter backdrop's. cv-universe.js views it head-on and
     moves it into the medallion with a lens shift.
   - The medallion dissolves. A vignette a little wider than the medallion
     fades the bust out. No loose dust: every point is rigid and on the face
     (the old ring drifted off the crown with the noise field).
   - Two blocks. The program's text block, then the portrait's sky (code.js
     portraitSky: a desktop field and an explicit phone layer), then every
     write left: more of the same tone walk, carried on where the first block
     stopped. About 84% of the budget is the face. In each block the writes
     are ranked by slot, the stars and glasses lowest (every cut keeps them),
     so a cut keeps an even prefix of the walk.
   - One sky with the program. programPortrait writes the same text block, the
     same sky on the same seed (no shared rng is touched before it) and parks
     its last block on its own ink at size 0: the stars stand still and the
     face's extra points fly into the text and go out there.
   ========================================================================== */

const SHARE = Object.freeze({ glasses: 0.006, dust: 0 });
export const KIND = Object.freeze({ star: 0, glasses: 1, tone: 3, dust: 4 });
// The share of the budget the portrait's sky leaves to the second block.
const PORTRAIT_SPARE = 1 - TEXT_SHARE - PORTRAIT_SPLIT[0] - PORTRAIT_SPLIT[1];
const PHI_INV = 0.6180339887498949;

// Features in photo units (u right, v down, 0..1), measured on the 1254 px
// original. Rims are ellipses; `glint` is the angle (radians, from +u toward
// +v) where each catches the light.
const RIMS = [
  { c: [0.3983, 0.4095], r: [0.0683, 0.0612], glint: 5.5 },
  { c: [0.6008, 0.4124], r: [0.0681, 0.0616], glint: 5.24 },
];
const BRIDGE = [[0.4665, 0.3876], [0.4745, 0.3740], [0.5255, 0.3740], [0.5335, 0.3844]];
const HINGES = [[[0.3301, 0.3796], [0.3030, 0.3788]], [[0.6691, 0.3844], [0.6954, 0.3812]]];
const STARS = [
  { at: [0.4067, 0.3756], size: 0.3, lift: 0.0 },
  { at: [0.5941, 0.3764], size: 0.29, lift: 0.0 },
  { at: [0.4514, 0.3652], size: 0.42, lift: 0.03 },
  { at: [0.6396, 0.3549], size: 0.38, lift: 0.03 },
  { at: [0.3301, 0.3812], size: 0.3, lift: 0.03 },
];

const clamp01 = (x) => (x < 0 ? 0 : x > 1 ? 1 : x);
const smooth = (a, b, x) => {
  const t = clamp01((x - a) / (b - a));
  return t * t * (3 - 2 * t);
};

function bytes(b64) {
  const s = typeof atob === 'function' ? atob(b64) : Buffer.from(b64, 'base64').toString('binary');
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

// Bilinear at (u, v) on an n x n grid of texel centres.
function bilinear(g, n, u, v) {
  let fx = u * n - 0.5, fy = v * n - 0.5;
  fx = fx < 0 ? 0 : fx > n - 1 ? n - 1 : fx;
  fy = fy < 0 ? 0 : fy > n - 1 ? n - 1 : fy;
  const x0 = fx | 0, y0 = fy | 0;
  const x1 = x0 + 1 < n ? x0 + 1 : x0, y1 = y0 + 1 < n ? y0 + 1 : y0;
  const tx = fx - x0, ty = fy - y0;
  const a = g[y0 * n + x0], b = g[y0 * n + x1], c = g[y1 * n + x0], d = g[y1 * n + x1];
  return (a + (b - a) * tx) * (1 - ty) + (c + (d - c) * tx) * ty;
}

// A separable (2r + 1)^2 filter: max, min or mean (over the samples in
// bounds). One loop per kind: the bake runs these over 1.6 million samples,
// and a kind test inside the inner loop cost as much as the work.
function filter2(src, n, r, kind) {
  const tmp = new Float32Array(n * n), out = new Float32Array(n * n);
  const pass = kind === 'mean' ? passMean : kind === 'min' ? passMin : passMax;
  pass(src, tmp, n, r, true);
  pass(tmp, out, n, r, false);
  return out;
}
function passMin(from, to, n, r, horizontal) {
  for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) {
    let m = Infinity;
    if (horizontal) {
      const row = y * n, b = Math.min(n - 1, x + r);
      for (let xx = Math.max(0, x - r); xx <= b; xx++) { const v = from[row + xx]; if (v < m) m = v; }
    } else {
      const b = Math.min(n - 1, y + r);
      for (let yy = Math.max(0, y - r); yy <= b; yy++) { const v = from[yy * n + x]; if (v < m) m = v; }
    }
    to[y * n + x] = m;
  }
}
function passMax(from, to, n, r, horizontal) {
  for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) {
    let m = -Infinity;
    if (horizontal) {
      const row = y * n, b = Math.min(n - 1, x + r);
      for (let xx = Math.max(0, x - r); xx <= b; xx++) { const v = from[row + xx]; if (v > m) m = v; }
    } else {
      const b = Math.min(n - 1, y + r);
      for (let yy = Math.max(0, y - r); yy <= b; yy++) { const v = from[yy * n + x]; if (v > m) m = v; }
    }
    to[y * n + x] = m;
  }
}
function passMean(from, to, n, r, horizontal) {
  for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) {
    let m = 0, c = 0;
    if (horizontal) {
      const row = y * n, b = Math.min(n - 1, x + r);
      for (let xx = Math.max(0, x - r); xx <= b; xx++) { m += from[row + xx]; c++; }
    } else {
      const b = Math.min(n - 1, y + r);
      for (let yy = Math.max(0, y - r); yy <= b; yy++) { m += from[yy * n + x]; c++; }
    }
    to[y * n + x] = m / c;
  }
}

function maxFilter(src, n, r) {
  const tmp = new Float32Array(n * n), out = new Float32Array(n * n);
  for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) {
    let m = 0;
    for (let d = -r; d <= r; d++) { const xx = x + d; if (xx >= 0 && xx < n && src[y * n + xx] > m) m = src[y * n + xx]; }
    tmp[y * n + x] = m;
  }
  for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) {
    let m = 0;
    for (let d = -r; d <= r; d++) { const yy = y + d; if (yy >= 0 && yy < n && tmp[yy * n + x] > m) m = tmp[yy * n + x]; }
    out[y * n + x] = m;
  }
  return out;
}

// Tone to point density: dense where the photo is lit, never empty where it
// is dark, so the shadows read as dim points rather than holes.
const toneDensity = (t) => 0.16 + 0.84 * Math.pow(clamp01(t), 1.15);
// A point's light (its size; energy goes as size squared): with the density
// above, the light per area follows the photo's tone at about display gamma,
// so the portrait reads as the photo, not as a stylised stipple.
const toneSize = (t) => 0.05 + 0.24 * Math.pow(clamp01(t), 0.95);
// The bust fades out a little past the medallion's circle (radius 0.5), and
// sooner below the hand than above the hair.
const vignette = (u, v) => {
  const dx = (u - 0.5) / 0.5, dy = (v - 0.46) / (v < 0.46 ? 0.56 : 0.5);
  return 1 - smooth(0.8, 1.02, Math.sqrt(dx * dx + dy * dy));
};

// The maps, from the document's JSON island, or null where there is none.
function island() {
  if (typeof document === 'undefined') return null;
  const el = document.getElementById('cv-avatar-data');
  if (!el) return null;
  try {
    const d = JSON.parse(el.textContent);
    return d && d.tone && d.depth ? d : null;
  } catch (_) {
    return null;
  }
}

let MAPS;
function maps() {
  if (MAPS !== undefined) return MAPS;
  const src = island();
  if (!src) return (MAPS = null);
  const N = src.tone.w, M = src.depth.w;
  const tb = bytes(src.tone.data), db = bytes(src.depth.data);
  const tone = new Float32Array(N * N), depth = new Float32Array(M * M);
  for (let i = 0; i < N * N; i++) tone[i] = tb[i] / 255;
  for (let i = 0; i < M * M; i++) depth[i] = db[i] / 255;
  /* The surface the points sit on: the depth map grown two texels past the
     silhouette (so the edge points sit on the person, not on the backdrop)
     and smoothed twice. A smooth surface, not a snapped one: snapping each
     cell across a jump to its near side (the hand before the chin) moved the
     depth map's staircase of 128 px cells as whole blocks under the rock and
     left square gaps round the fingers. At this relief, seen head-on, the
     smooth ramp between hand and chin does not show. */
  const surf = filter2(filter2(maxFilter(depth, M, 2), M, 1, 'mean'), M, 1, 'mean');
  /* The tone at the silhouette. The photo's backdrop is a lighter grey than
     the beard, the shirt and the hair, and a texel on the edge averages in
     some of it, so the edge lit up as a bright rim. Within three texels of
     the backdrop the tone is the darkest of the person's own tones round it. */
  const dT = new Float32Array(N * N);
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) dT[y * N + x] = bilinear(depth, M, (x + 0.5) / N, (y + 0.5) / N);
  const nearBg = filter2(dT, N, 3, 'min');
  const own = new Float32Array(N * N);
  for (let i = 0; i < N * N; i++) own[i] = dT[i] > 0.3 ? tone[i] : 1;
  const ownMin = filter2(own, N, 2, 'min');
  const mask = new Float32Array(N * N), rhoT = new Float32Array(N * N);
  let sumT = 0, maxT = 0;
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const i = y * N + x, u = (x + 0.5) / N, v = (y + 0.5) / N;
    const edge = 1 - smooth(0.18, 0.32, nearBg[i]);
    if (edge > 0 && ownMin[i] < 1) tone[i] += (Math.min(tone[i], ownMin[i]) - tone[i]) * edge;
    // Tight to the person: the depth map's soft halo of stray hair at the
    // crown is left out, so no dots float off the head.
    const m = smooth(0.24, 0.34, dT[i]);
    mask[i] = m;
    rhoT[i] = m * vignette(u, v) * toneDensity(tone[i]);
    sumT += rhoT[i];
    if (rhoT[i] > maxT) maxT = rhoT[i];
  }
  /* Where the tone's bilinear read is exactly 0 (its four texels all 0: the
     backdrop, the vignette's corners), flagged per texel so the walk can skip
     those candidates without the read or the coin. The same clamped
     neighbourhood bilinear() reads, so a skipped candidate is exactly one
     the test would have rejected. */
  const nzT = new Uint8Array(N * N);
  for (let y = 0; y < N; y++) {
    const y1 = y + 1 < N ? y + 1 : y;
    for (let x = 0; x < N; x++) {
      const x1 = x + 1 < N ? x + 1 : x;
      nzT[y * N + x] = rhoT[y * N + x] > 0 || rhoT[y * N + x1] > 0 || rhoT[y1 * N + x] > 0 || rhoT[y1 * N + x1] > 0 ? 1 : 0;
    }
  }
  MAPS = { N, M, tone, depth, surf, mask, rhoT, nzT, meanT: sumT / (N * N), maxT };
  return MAPS;
}

// The Roberts generators for d = 2 (R2), recovered from point 1 exactly as
// sampling.js jittered() does, so the walk is the library's own sequence.
const R2G = (() => {
  const a = rd(1, 2);
  return [(a[0] + 0.5) % 1, (a[1] + 0.5) % 1];
})();

/* n points of a density, in walk order (every prefix even, and so is every
   later stretch of the walk): R2 over the square, each candidate kept by a
   fixed coin weighted by the density (a third R2 coordinate as the coin
   correlates with the first and lays the kept points in stripes), then moved
   by up to 0.4 of the spacing at `nRef` points so no lattice rows show.
   `state` continues an earlier walk ({ k, got }), which is how the block after
   the sky carries on where the block before it stopped. `lo..hi` maps the
   unit square onto the photo (the dust walks a wider square). */
function walk(n, rho, rhoMax, mean, nRef, salt, state = { k: 0, got: 0 }, lo = 0, hi = 1, nz = null) {
  const m = maps();
  const N = m.N;
  const out = new Float32Array(n * 2);
  const span = hi - lo;
  const limit = state.k + 400 * n + 10000;
  let k = state.k, got = 0;
  for (; got < n && k < limit; k++) {
    const p0 = (0.5 + R2G[0] * k) % 1, p1 = (0.5 + R2G[1] * k) % 1;
    const u = lo + span * p0, v = lo + span * p1;
    if (nz) {
      // bilinear()'s own texel: a candidate on four zero texels reads 0.
      let fx = u * N - 0.5, fy = v * N - 0.5;
      fx = fx < 0 ? 0 : fx > N - 1 ? N - 1 : fx;
      fy = fy < 0 ? 0 : fy > N - 1 ? N - 1 : fy;
      if (nz[(fy | 0) * N + (fx | 0)] === 0) continue;
    }
    const r = rho(u, v, m);
    if (r <= 0 || hash01(salt + 0x5bd1e995 + k) * rhoMax >= r) continue;
    const sp = Math.sqrt(mean / (nRef * Math.max(r, 1e-4))) * span;
    const g = state.got + got;
    out[got * 2] = u + (hash01(salt + 2 * g) - 0.5) * 0.8 * sp;
    out[got * 2 + 1] = v + (hash01(salt + 2 * g + 1) - 0.5) * 0.8 * sp;
    got++;
  }
  const end = { k, got: state.got + got };
  for (; got < n; got++) { out[got * 2] = 0.5; out[got * 2 + 1] = 0.5; }
  return { pts: out, end };
}

const inPhoto = (u, v) => u >= 0 && u < 1 && v >= 0 && v < 1;
const rhoTone = (u, v, m) => (inPhoto(u, v) ? bilinear(m.rhoT, m.N, u, v) : 0);
// Dust: a faint ring where the vignette lets go, none past 1.2 radii.
const rhoDust = (u, v) => {
  const dx = (u - 0.5) / 0.5, dy = (v - 0.46) / 0.53;
  const r = Math.sqrt(dx * dx + dy * dy);
  return smooth(0.82, 0.98, r) * (1 - smooth(1.0, 1.2, r));
};

const PLANS = new Map();

// The arrays of a plan of T points, in priority order.
const planArrays = (T) => ({
  x: new Float32Array(T), y: new Float32Array(T), z: new Float32Array(T),
  size: new Float32Array(T), tint: new Float32Array(T), phase: new Float32Array(T), rig: new Float32Array(T).fill(1),
  // What each point is (KIND), for the studio's export; the shader never reads it.
  kind: new Uint8Array(T).fill(KIND.tone),
});

function hiddenPlan(T, slots) {
  const P = planArrays(T);
  P.x.fill(AVATAR.centre[0]); P.y.fill(AVATAR.centre[1]); P.z.fill(AVATAR.centre[2]);
  P.tint.fill(0.5); P.phase.fill(0.5);
  return { P, rank: slotRanks(slots), T, tone: { k: 0, got: 0 } };
}

// Photo units to world, on the depth map's surface.
function placer(m) {
  const [cx, cy, cz] = AVATAR.centre;
  const S = AVATAR.side;
  const depthAt = (u, v) => (inPhoto(u, v) ? bilinear(m.surf, m.M, u, v) : AVATAR.plane - 0.12);
  return {
    wx: (u) => cx + (u - 0.5) * S,
    wy: (v) => cy - (v - 0.5) * S,
    wz: (d) => cz + (d - AVATAR.plane) * AVATAR.relief,
    depthAt,
    sweep: (u, v, h) => 0.62 * (1 - v) + 0.2 * u + 0.08 * h,
  };
}

// One tone point: its light and colour are the photo's (shade cools a little
// toward the accent).
function toneAt(m, f, u, v, h) {
  const t = clamp01(bilinear(m.tone, m.N, u, v));
  return {
    z: f.wz(f.depthAt(u, v)),
    size: toneSize(t) * (0.94 + 0.12 * h),
    tint: 0.5 * Math.pow(1 - t, 1.5),
    phase: f.sweep(u, v, h),
  };
}

// Points a portrait of `count` spends, on the photo's own spacing.
const toneRef = (count) => Math.round(count * 0.84);

/* The block before the sky (the program's text block, write j the program's
   write j): the stars, the glasses, then the tone walk with a little dust
   merged in by fraction. */
function avatarPlan(count, slots) {
  const T = slots.length;
  // The points do not depend on the slots, the ranks do: keyed on both ends.
  const key = `A:${count}:${T}:${T ? slots[0] : 0}:${T ? slots[T - 1] : 0}`;
  const cached = PLANS.get(key);
  if (cached) return cached;
  const m = maps();
  if (!m) {
    const hidden = hiddenPlan(T, slots);
    PLANS.set(key, hidden);
    return hidden;
  }
  const f = placer(m);
  const P = planArrays(T);
  let r = 0;
  let cur = KIND.star;
  const put = (u, v, z, size, tint, phase, rig = 1) => {
    if (r >= T) return;
    P.x[r] = f.wx(u); P.y[r] = f.wy(v); P.z[r] = z;
    P.size[r] = size; P.tint[r] = tint; P.phase[r] = phase; P.rig[r] = rig; P.kind[r] = cur;
    r++;
  };

  // Stars first: every cut keeps them.
  STARS.forEach((s, i) => {
    const [u, v] = s.at;
    put(u, v, f.wz(f.depthAt(u, v) + s.lift) + 0.04, s.size, 0.02, f.sweep(u, v, hash01(77 + i)));
  });

  // The glasses, by length, each part on its own golden-ratio order.
  cur = KIND.glasses;
  const parts = [];
  RIMS.forEach((rim) => {
    const len = 2 * Math.PI * Math.sqrt((rim.r[0] * rim.r[0] + rim.r[1] * rim.r[1]) / 2);
    parts.push({ len, at: (t) => {
      const th = t * 2 * Math.PI;
      const lit = Math.pow(Math.max(0, Math.cos(th - rim.glint)), 2);
      return [rim.c[0] + Math.cos(th) * rim.r[0], rim.c[1] + Math.sin(th) * rim.r[1], lit];
    } });
  });
  const cubic = (p, t) => {
    const s = 1 - t;
    return [0, 1].map((i) => s * s * s * p[0][i] + 3 * s * s * t * p[1][i] + 3 * s * t * t * p[2][i] + t * t * t * p[3][i]);
  };
  parts.push({ len: 0.075, at: (t) => [...cubic(BRIDGE, t), 0.35 + 0.4 * (1 - Math.abs(t - 0.5) * 2)] });
  HINGES.forEach(([a, b]) => {
    parts.push({ len: Math.hypot(b[0] - a[0], b[1] - a[1]), at: (t) => [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, 0.55] });
  });
  const nGlass = Math.max(40, Math.round(T * SHARE.glasses));
  const totalLen = parts.reduce((s, p) => s + p.len, 0);
  const glass = [];
  parts.forEach((p) => {
    const n = Math.max(6, Math.round((nGlass * p.len) / totalLen));
    for (let k = 0; k < n; k++) glass.push({ p, t: (0.5 + k * PHI_INV) % 1, key: (k + 0.5) / n });
  });
  glass.sort((a, b) => a.key - b.key);
  glass.forEach((g, i) => {
    const [u, v, lit] = g.p.at(g.t);
    put(u, v, f.wz(f.depthAt(u, v) + 0.03), 0.14 + 0.09 * lit, 0.25 - 0.2 * lit, f.sweep(u, v, hash01(901 + i)));
  });

  // Tone and dust, merged by fraction so every prefix holds its share of both.
  const left = T - r;
  const nD = Math.round(left * SHARE.dust);
  const nT = Math.max(0, left - nD);
  const tone = walk(nT, rhoTone, m.maxT, m.meanT, toneRef(count), 0x40000, undefined, 0, 1, m.nzT);
  const dust = walk(nD, rhoDust, 1, 0.12, Math.max(1, nD), 0x90000, undefined, -0.12, 1.12);
  let it = 0, id = 0;
  while (it < nT || id < nD) {
    const kt = it < nT ? (it + 0.5) / nT : Infinity, kd = id < nD ? ((id + 0.5) / nD) * 1.05 : Infinity;
    if (kt <= kd) {
      cur = KIND.tone;
      const u = tone.pts[it * 2], v = tone.pts[it * 2 + 1];
      const p = toneAt(m, f, u, v, hash01(0x50000 + it));
      put(u, v, p.z, p.size, p.tint, p.phase);
      it++;
    } else {
      cur = KIND.dust;
      const u = dust.pts[id * 2], v = dust.pts[id * 2 + 1];
      const h1 = hash01(0xa0000 + 3 * id), h2 = hash01(0xa0001 + 3 * id), h3 = hash01(0xa0002 + 3 * id);
      put(u, v, f.wz(f.depthAt(u, v)) + (h2 - 0.6) * 1.6, 0.07 + 0.08 * h1 * h1, 0.6 + 0.35 * h3, f.sweep(u, v, h2), 0.1 + 0.3 * h3);
      id++;
    }
  }
  for (; r < T;) put(0.5, 0.45, AVATAR.centre[2], 0, 0.5, 0.5);

  const plan = { P, rank: slotRanks(slots), T, tone: tone.end };
  PLANS.set(key, plan);
  return plan;
}

/* The block after the sky (every write the program leaves parked): more of
   the same tone walk, carried on from where the first block stopped, so the
   face gets the whole spare budget and stays one even set. */
function avatarMore(count, slots, before) {
  const T = slots.length;
  const key = `B:${count}:${T}:${T ? slots[0] : 0}:${T ? slots[T - 1] : 0}`;
  const cached = PLANS.get(key);
  if (cached) return cached;
  const m = maps();
  if (!m) {
    const hidden = hiddenPlan(T, slots);
    PLANS.set(key, hidden);
    return hidden;
  }
  const f = placer(m);
  const P = planArrays(T);
  const tone = walk(T, rhoTone, m.maxT, m.meanT, toneRef(count), 0x40000, before.tone, 0, 1, m.nzT);
  for (let i = 0; i < T; i++) {
    const u = tone.pts[i * 2], v = tone.pts[i * 2 + 1];
    const p = toneAt(m, f, u, v, hash01(0x70000 + i));
    P.x[i] = f.wx(u); P.y[i] = f.wy(v); P.z[i] = p.z;
    P.size[i] = p.size; P.tint[i] = p.tint; P.phase[i] = p.phase;
  }
  const plan = { P, rank: slotRanks(slots), T };
  PLANS.set(key, plan);
  return plan;
}

export const AVATAR_PIVOT = Object.freeze([AVATAR.centre[0], AVATAR.centre[1] - 0.4, AVATAR.centre[2] + 0.5]);

/* The portrait on its own, without the registry or the sky: its points in
   priority order (world units, KIND per point), for avatar-studio.html. */
export function avatarPoints(count = 100000) {
  const T1 = textBlock(count);
  const ids = (a, n) => { const o = new Uint32Array(n); for (let i = 0; i < n; i++) o[i] = a + i; return o; };
  const first = avatarPlan(count, ids(0, T1));
  const more = avatarMore(count, ids(T1, Math.round(count * PORTRAIT_SPARE)), first);
  const join = (k, A) => { const o = new A(first.T + more.T); o.set(first.P[k]); o.set(more.P[k], first.T); return o; };
  const out = {};
  ['x', 'y', 'z', 'size', 'tint', 'phase', 'rig'].forEach((k) => { out[k] = join(k, Float32Array); });
  out.kind = join('kind', Uint8Array);
  return out;
}

export const avatar = {
  // mainfn's seed: the sky after the block is programPortrait's (see portraitSky).
  seed: 0x3a1a,
  mode: MODE.ROCK_Y,
  pivot: AVATAR_PIVOT,
  touch: { mode: TOUCH.RIPPLE, radius: 2.4, strength: 0.65 },
  build(c) {
    const write = ({ P, rank, T }) => {
      for (let j = 0; j < T; j++) {
        const q = rank[j];
        c.write(P.x[q], P.y[q], P.z[q], P.size[q], P.tint[q], P.phase[q], AVATAR.rock, P.rig[q]);
      }
    };
    const first = avatarPlan(c.count, c.ahead(textBlock(c.count)));
    write(first);
    portraitSky(c);
    write(avatarMore(c.count, c.ahead(c.count - c.cursor), first));
  },
};
